### ISSUE TITLE
Problem with order in write_spinsys function

### ISSUE THREAD

**Issue by carlosbornes** [CCP-NC/soprano#29]
I've noticed that the header from the `write_spinsys` function in `soprano.calculate.nmr.simpson` is very unstable when ordering the nuclei in the `channels` line. I believe this is related to the `set` function.

As far as I understand, Simpson requires that the first nucleus to appear in the channels is the nucleus to be observed. I've added a function to enforce the ordering of nuclei in channels by using the key `obs_nuc` and opened a pull request #28

**Comment by jkshenton** [comment]
Fixed in https://github.com/CCP-NC/soprano/pull/28
